- publisher:
    name: ci-pipeline-ostree-image-publisher
    publishers:
        - conditional-publisher:
            - condition-kind: shell
              condition-command: |
                  prev=$(curl $JENKINS_URL/job/{compose_job}/lastBuild/api/json 2>/dev/null | jq '.timestamp' | cut -c1-10)
                  cur=$(date +%s)
                  elapsed=$((cur - prev))
                  if [ $elapsed -gt 86400 ]; then
                     exit 0
                  fi
                  exit 1
              action:
                  - trigger-parameterized-builds:
                      - project: '{compose_job}'
                        current-parameters: true
                        block: true
                        same-node: true

- job:
    name: ci-pipeline-ostree-compose
    defaults: ci-pipeline-defaults
    builders:
        - ci-pipeline-duffy-builder:
            task: ostree-compose
            playbook: sig-atomic-buildscripts/centos-ci/setup/setup-system.yml

    publishers:
        - ci-pipeline-duffy-publisher
        - ci-pipeline-ostree-image-publisher:
            compose_job: ci-pipeline-ostree-image-compose

- job:
    name: ci-pipeline-ostree-image-compose
    defaults: ci-pipeline-defaults
    builders:
        - ci-pipeline-duffy-builder:
            task: ostree-image-compose

    publishers:
        - ci-pipeline-duffy-publisher
