---
- hosts: localhost
  connection: local
  tasks:
    - name: "Install openshift"
      shell: ansible-playbook -i /tmp/singlenode.inv --private-key /root/.ssh/ex /root/linchpin_workspace/hooks/ansible/openshift-ansible/playbooks/byo/config.yml -e'openshift_disable_check=disk_availability,docker_storage,memory_availability' -e 'ansible_python_interpreter=/usr/bin/python3'
      register: openshift_out
    - name: "Copy contents to openshift log"
      copy:
        content: "{{ openshift_out }}"
        dest: "/tmp/openshift_install.log"
